<?php $measuringUnitKeys =[
    // "id" => "id",
    // "Brand" =>"Brand",
    // "Model" => "Model",
    // "Generation" =>  "Generation", 
    // "Modification (Engine)" =>"Modification (Engine)",
    // "Start of production" => "Start of production",
    // "End of production" => "End of production",
    // "Powertrain Architecture" => "Powertrain Architecture",
    // "Body type" => "Body type",
    // "Seats" => "Seats",
    // "Doors" => "Doors",

    "Fuel consumption (economy) - urban" => "Fuel consumption (economy) - urban (l∕100 km)",
    "Fuel consumption (economy) - extra urban" => "Fuel consumption (economy) - extra urban (l∕100 km)",
    "Fuel consumption (economy) - combined" => "Fuel consumption (economy) - combined (l∕100 km)",
    "Fuel consumption (economy) - urban (Ethanol - E85)" => "Fuel consumption (economy) - urban (Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - extra urban (Ethanol - E85)" => "Fuel consumption (economy) - extra urban(Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - combined (Ethanol - E85)" => "Fuel consumption (economy) - combined(Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - urban (LPG)" => "Fuel consumption (economy) - urban (LPG)(l∕100 km)",
    "Fuel consumption (economy) - extra urban (LPG)" => "Fuel consumption (economy) - extra urban (LPG)(l∕100 km)",
    "Fuel consumption (economy) - combined (LPG)" => "Fuel consumption (economy) - combined (LPG)(l∕100 km)",
    "Fuel consumption (economy) - urban (CNG)" => "Fuel consumption (economy) - urban (CNG)(kg∕100 km)",
    "Fuel consumption (economy) - extra urban (CNG)" => "Fuel consumption (economy) - extra urban (CNG)(kg∕100 km)",
    "Fuel consumption (economy) - combined (CNG)" => "Fuel consumption (economy) - combined (CNG)(kg∕100 km)",
 
    "Fuel tank capacity" => "Fuel tank capacity (l)",
    "Fuel tank capacity (LPG)" => "Fuel tank capacity (LPG)(l)",
    "CNG cylinder capacity" => "CNG cylinder capacity (kg)",
    
    "CO" => "CO (g∕km)",
    // "Emission standard" => "Emission standard",
    "AdBlue tank" => "AdBlue tank (l)",
    // "Fuel Type" => "Fuel Type",

    "Average Energy consumption" => "Average Energy consumption(kWh∕100 km)",
    "Battery voltage" => "Battery voltage (V)",
    // "Battery technology" => "Battery technology",
    "Gross battery capacity" => "Gross battery capacity (kWh)",
    "Net (usable) battery capacity" => "Net (usable) battery capacity (kWh)" ,
    "Recuperation output" =>  "Recuperation output (kW)",

    "All-electric range" =>  "All-electric range (km)",

    "Drag coefficient (C" => "Aerodynamic drag coefficient (Cₓ)",
    
    "Acceleration 0 - 100 km/h" => "Acceleration 0 - 100 km∕h (sec)",
    "Acceleration 0 - 100 km/h (LPG)" => "Acceleration 0 - 100 km∕h (LPG)(sec)",
    "Acceleration 0 - 100 km/h (CNG)" => "Acceleration 0 - 100 km∕h (CNG)(sec)",
    "Acceleration 0 - 300 km/h" => "Acceleration 0 - 300 km∕h (sec)",
    "Acceleration 0 - 200 km/h" => "Acceleration 0 - 200 km∕h (sec)",
    "Acceleration 0 - 62 mph" => "Acceleration 0 - 62 mph (sec)",
    "Acceleration 0 - 60 mph" => "Acceleration 0 - 60 mph (sec)",
    "Maximum speed" => "Maximum speed (km∕h)",
    "Maximum speed (LPG)" => "Maximum speed (LPG)(km∕h)",
    "Maximum speed (CNG)" => "Maximum speed (CNG)(km∕h)",
    "Max speed (electric)" =>"Maximum speed (electric) (km∕h)",
   
    "Maximum engine speed" => "Maximum engine speed rpm.",

    "Power" => "Power (Hp)",
    "Power (LPG)" => "Power (LPG)(Hp)",
    "Power (CNG)" => "Power (CNG)(Hp)",
    "Power (Ethanol - E85)" => "Power (Ethanol - E85)(Hp)",
    "System power" => "System power (Hp)",

    "Max power rpm."=>"Max power rpm.", 
    "Max power (LPG) rpm."=>"Max power (LPG) rpm.", 
    "Max power (CNG) rpm."=>"Max power (CNG) rpm.", 
    "Max power (Ethanol - E85) rpm."=>"Max power (Ethanol - E85) rpm.", 
    "Max system power rpm." => "Max system power rpm.",
    
    "Weight-to-power ratio" => "Weight-to-power ratio (kg∕Hp)",
    "Weight-to-power ratio (Hp∕tonne)" => "Weight-to-power ratio (Hp∕tonne)",
    
    "Torque" => "Torque (Nm)",
    "Torque (LPG)" => "Torque (LPG)(Hp)",
    "Torque (CNG)" => "Torque (CNG)(Hp)",
    "Torque (Ethanol - E85)" => "Torque (Ethanol - E85)(Hp)",
    "System torque" =>  "System torque (Nm)",
  
    "Max torque rpm."=>"Max torque rpm.", 
    "Max torque (LPG) rpm."=>"Max torque (LPG) rpm.", 
    "Max torque (CNG) rpm."=>"Max torque (CNG) rpm.", 
    "Max torque (Ethanol - E85) rpm."=>"Max torque (Ethanol - E85) rpm.", 
    "Max system torque rpm."=>"Max system torque rpm.", 

    "Weight-to-torque ratio"=> "Weight-to-torque ratio (kg∕Nm)",
    "Weight-to-torque ratio (Nm∕tonne)"=> "Weight-to-torque ratio (Nm∕tonne)",

    "Power per litre" => "Power per litre (Hp∕l)",
    "Power per litre (LPG)" => "Power per litre (LPG)(Hp∕l)",
    "Power per litre (CNG)" => "Power per litre (CNG)(Hp∕l)",
    "Power per litre (Ethanol - E85)" => "Power per litre (Ethanol - E85)(Hp∕l)",
   
    // "Engine Model/Code" => "Engine Model∕Code",
    // "Engine location" => "Engine location",
    "Engine displacement" => "Engine displacement (cm³)",
    // "Number of cylinders" => "Number of cylinders",
    // "Position of cylinders" => "Position of cylinders",
    // "Compression ratio" =>  "Compression ratio",
    // "Number of valves per cylinder" => "Number of valves per cylinder",
    // "Engine aspiration" => "Engine aspiration",
    // "Engine systems" =>  "Engine systems",
    
    "Cylinder Bore" => "Cylinder Bore (mm)",
    "Piston Stroke" => "Piston Stroke (mm)",
    "Engine oil capacity" => "Engine oil capacity (l)",
    "Coolant" => "Coolant (l)",         
    // "Oil viscosity" =>  "Oil viscosity",
    // "Engine oil specification" => "Engine oil specification", 
    "Kerb Weight" => "Kerb weight (kg)",
    "Max. weight" => "Max. weight (kg)",
    "Max load" => "Max load (kg)",
    "Trunk (boot) space - minimum" => "Trunk (boot) space - minimum (l)",
    "Trunk (boot) space - maximum" => "Trunk (boot) space - maximum (l)",  
    "Max. roof load" => "Max. roof load (kg)",
    "Permitted trailer load with brakes (12%)"=>"Permitted trailer load with brakes 12% (kg)",
    "Permitted trailer load with brakes (8%)"=>"Permitted trailer load with brakes 8% (kg)",
    "Permitted trailer load without brakes" => "Permitted trailer load without brakes (kg)",
    "Permitted towbar download" => "Permitted towbar download (kg)",
    "Length" => "Length (mm)",
    "Width" => "Width (mm)",
    "Width including mirrors" => "Width including mirrors (mm)",
    "Width with mirrors folded" => "Width with mirrors folded (mm)",
    "Height" => "Height (mm)",
    "Wheelbase" => "Wheelbase (mm)",
    "Front track" => "Front track (mm)", 
    "Rear (Back) track" => "Rear (Back) track (mm)",
    "Front overhang" =>"Front overhang (mm)",
    "Rear overhang" => "Rear overhang (mm)",
    "Minimum turning circle (turning diameter)" => "Minimum u-turn diameter (m)",
    "Ride height (ground clearance)" =>  "Ground clearance (mm)",
    "Wading depth" =>  "Wading depth (mm)",
    "Approach angle" => "Approach angle (%)",
    "Ramp-over (brakeover) angle" => "Ramp-over (brakeover) angle (%)",
    "Departure angle" => "Departure angle (%)",
    "Climb angle" =>  "Climb angle (%)",
    // "Drive wheel" => "Drive wheel",
    // "Drivetrain Architecture" =>"Drivetrain Architecture",
    // "Number of Gears (manual transmission)" => "Number of Gears (manual transmission)",
    // "Number of Gears (automatic transmission)" => "Number of Gears (automatic transmission)",
    // "Front suspension" => "Front suspension",
    // "Rear suspension" => "Rear suspension",
    // "Front brakes" => "Front brakes",
    // "Rear brakes" => "Rear brakes",
    // "Assisting systems" =>  "Assisting systems",
    "200 km/h - 0" => "200 km∕h - 0 (m)",
    "100 km/h - 0" => "100 km∕h - 0 (m)",
    // "Steering type" => "Steering type",
    // "Power steering" =>  "Power steering",
    // "Tires size" =>  "Tires size",
    // "Wheel rims size" => "Wheel rims size",
   
    // "Fuel System" => "Fuel System",
    // "Valvetrain" => "Valvetrain",  
];

  //"reverse" of $measuringUnitKeys
  $uncountableKeys =[
    "id" => "id",
    "Brand" =>"Brand",
    "Model" => "Model",
    "Generation" =>  "Generation", 
    "Modification (Engine)" =>"Modification (Engine)",
    "Start of production" => "Start of production",
    "End of production" => "End of production",
    "Powertrain Architecture" => "Powertrain Architecture",
    "Body type" => "Body type",
    "Seats" => "Seats",
    "Doors" => "Doors",

    // "Fuel consumption (economy) - urban" => "Fuel consumption (economy) - urban (l∕100 km)",
    // "Fuel consumption (economy) - extra urban" => "Fuel consumption (economy) - extra urban (l∕100 km)",
    // "Fuel consumption (economy) - combined" => "Fuel consumption (economy) - combined (l∕100 km)",
    // "Fuel consumption (economy) - urban (Ethanol - E85)" => "Fuel consumption (economy) - urban (Ethanol - E85)(l∕100 km)",
    // "Fuel consumption (economy) - extra urban (Ethanol - E85)" => "Fuel consumption (economy) - extra urban(Ethanol - E85)(l∕100 km)",
    // "Fuel consumption (economy) - combined (Ethanol - E85)" => "Fuel consumption (economy) - combined(Ethanol - E85)(l∕100 km)",
    // "Fuel consumption (economy) - urban (LPG)" => "Fuel consumption (economy) - urban (LPG)(l∕100 km)",
    // "Fuel consumption (economy) - extra urban (LPG)" => "Fuel consumption (economy) - extra urban (LPG)(l∕100 km)",
    // "Fuel consumption (economy) - combined (LPG)" => "Fuel consumption (economy) - combined (LPG)(l∕100 km)",
    // "Fuel consumption (economy) - urban (CNG)" => "Fuel consumption (economy) - urban (CNG)(kg∕100 km)",
    // "Fuel consumption (economy) - extra urban (CNG)" => "Fuel consumption (economy) - extra urban (CNG)(kg∕100 km)",
    // "Fuel consumption (economy) - combined (CNG)" => "Fuel consumption (economy) - combined (CNG)(kg∕100 km)",
 
    // "Fuel tank capacity" => "Fuel tank capacity (l)",
    // "Fuel tank capacity (LPG)" => "Fuel tank capacity (LPG)(l)",
    // "CNG cylinder capacity" => "CNG cylinder capacity (kg)",
    
    // "CO" => "CO (g∕km)",
    "Emission standard" => "Emission standard",
    // "AdBlue tank" => "AdBlue tank (l)",
    "Fuel Type" => "Fuel Type",

    // "Average Energy consumption" => "Average Energy consumption(kWh∕100 km)",
    // "Battery voltage" => "Battery voltage (V)",
    "Battery technology" => "Battery technology",
    // "Gross battery capacity" => "Gross battery capacity (kWh)",
    // "Net (usable) battery capacity" => "Net (usable) battery capacity (kWh)" ,
    // "Recuperation output" =>  "Recuperation output (kW)",

    // "All-electric range" =>  "All-electric range (km)",

    // "Drag coefficient (C" => "Aerodynamic drag coefficient (Cₓ)",
    
    // "Acceleration 0 - 100 km/h" => "Acceleration 0 - 100 km∕h (sec)",
    // "Acceleration 0 - 100 km/h (LPG)" => "Acceleration 0 - 100 km∕h (LPG)(sec)",
    // "Acceleration 0 - 100 km/h (CNG)" => "Acceleration 0 - 100 km∕h (CNG)(sec)",
    // "Acceleration 0 - 300 km/h" => "Acceleration 0 - 300 km∕h (sec)",
    // "Acceleration 0 - 200 km/h" => "Acceleration 0 - 200 km∕h (sec)",
    // "Acceleration 0 - 62 mph" => "Acceleration 0 - 62 mph (sec)",
    // "Acceleration 0 - 60 mph" => "Acceleration 0 - 60 mph (sec)",
    // "Maximum speed" => "Maximum speed (km∕h)",
    // "Maximum speed (LPG)" => "Maximum speed (LPG)(km∕h)",
    // "Maximum speed (CNG)" => "Maximum speed (CNG)(km∕h)",
    // "Max speed (electric)" =>"Maximum speed (electric) (km∕h)",
   
    // "Maximum engine speed" => "Maximum engine speed rpm.",

    // "Power" => "Power (Hp)",
    // "Power (LPG)" => "Power (LPG)(Hp)",
    // "Power (CNG)" => "Power (CNG)(Hp)",
    // "Power (Ethanol - E85)" => "Power (Ethanol - E85)(Hp)",
    // "System power" => "System power (Hp)",

    // "Max power rpm."=>"Max power rpm.", 
    // "Max power (LPG) rpm."=>"Max power (LPG) rpm.", 
    // "Max power (CNG) rpm."=>"Max power (CNG) rpm.", 
    // "Max power (Ethanol - E85) rpm."=>"Max power (Ethanol - E85) rpm.", 
    // "Max system power rpm." => "Max system power rpm.",
    
    // "Weight-to-power ratio" => "Weight-to-power ratio (kg∕Hp)",
    // "Weight-to-power ratio (Hp∕tonne)" => "Weight-to-power ratio (Hp∕tonne)",  
  
    // "Torque" => "Torque (Nm)",
    // "Torque (LPG)" => "Torque (LPG)(Hp)",
    // "Torque (CNG)" => "Torque (CNG)(Hp)",
    // "Torque (Ethanol - E85)" => "Torque (Ethanol - E85)(Hp)",
    // "System torque" =>  "System torque (Nm)",

    // "Max torque rpm."=>"Max torque rpm.", 
    // "Max torque (LPG) rpm."=>"Max torque (LPG) rpm.", 
    // "Max torque (CNG) rpm."=>"Max torque (CNG) rpm.", 
    // "Max torque (Ethanol - E85) rpm."=>"Max torque (Ethanol - E85) rpm.", 
    // "Max system torque rpm."=>"Max system torque rpm.", 

    // "Weight-to-torque ratio"=> "Weight-to-torque ratio (kg∕Nm)",
    // "Weight-to-torque ratio (Nm∕tonne)"=> "Weight-to-torque ratio (Nm∕tonne)",

    // "Power per litre" => "Power per litre (Hp∕l)",
    // "Power per litre (LPG)" => "Power per litre (LPG)(Hp∕l)",
    // "Power per litre (CNG)" => "Power per litre (CNG)(Hp∕l)",
    // "Power per litre (Ethanol - E85)" => "Power per litre (Ethanol - E85)(Hp∕l)",
    "Engine Model/Code" => "Engine Model∕Code",
    "Engine location" => "Engine location",
    // "Engine displacement" => "Engine displacement (cm³)",
    "Number of cylinders" => "Number of cylinders",
    "Position of cylinders" => "Position of cylinders",
    "Compression ratio" =>  "Compression ratio",
    "Number of valves per cylinder" => "Number of valves per cylinder",
    "Engine aspiration" => "Engine aspiration",
    "Engine systems" =>  "Engine systems",
    // "Cylinder Bore" => "Cylinder Bore (mm)",
    // "Piston Stroke" => "Piston Stroke (mm)",
    // "Engine oil capacity" => "Engine oil capacity (l)",
    // "Coolant" => "Coolant (l)",         
    "Oil viscosity" =>  "Oil viscosity",
    "Engine oil specification" => "Engine oil specification", 
    // "Kerb Weight" => "Kerb weight (kg)",
    // "Max. weight" => "Max. weight (kg)",
    // "Max load" => "Max load (kg)",
    // "Trunk (boot) space - minimum" => "Trunk (boot) space - minimum (l)",
    // "Trunk (boot) space - maximum" => "Trunk (boot) space - maximum (l)",  
    // "Max. roof load" => "Max. roof load (kg)",
    // "Permitted trailer load with brakes (12%)"=>"Permitted trailer load with brakes 12% (kg)",
    // "Permitted trailer load with brakes (8%)"=>"Permitted trailer load with brakes 8% (kg)",
    // "Permitted trailer load without brakes" => "Permitted trailer load without brakes (kg)",
    // "Permitted towbar download" => "Permitted towbar download (kg)",
    // "Length" => "Length (mm)",
    // "Width" => "Width (mm)",
    // "Width including mirrors" => "Width including mirrors (mm)",
    // "Width with mirrors folded" => "Width with mirrors folded (mm)",
    // "Height" => "Height (mm)",
    // "Wheelbase" => "Wheelbase (mm)",
    // "Front track" => "Front track (mm)", 
    // "Rear (Back) track" => "Rear (Back) track (mm)",
    // "Front overhang" =>"Front overhang (mm)",
    // "Rear overhang" => "Rear overhang (mm)",
    // "Minimum turning circle (turning diameter)" => "Minimum u-turn diameter (m)",
    // "Ride height (ground clearance)" =>  "Ground clearance (mm)",
    // "Wading depth" =>  "Wading depth (mm)",
    // "Approach angle" => "Approach angle (%)",
    // "Ramp-over (brakeover) angle" => "Ramp-over (brakeover) angle (%)",
    // "Departure angle" => "Departure angle (%)",
    // "Climb angle" =>  "Climb angle (%)",
    "Drive wheel" => "Drive wheel",
    "Drivetrain Architecture" =>"Drivetrain Architecture",
    "Number of Gears (manual transmission)" => "Number of Gears (manual transmission)",
    "Number of Gears (automatic transmission)" => "Number of Gears (automatic transmission)",
    "Front suspension" => "Front suspension",
    "Rear suspension" => "Rear suspension",
    "Front brakes" => "Front brakes",
    "Rear brakes" => "Rear brakes",
    "Assisting systems" =>  "Assisting systems",
    // "200 km/h - 0" => "200 km∕h - 0 (m)",
    // "100 km/h - 0" => "100 km∕h - 0 (m)",
    "Steering type" => "Steering type",
    "Power steering" =>  "Power steering",
    "Tires size" =>  "Tires size",
    "Wheel rims size" => "Wheel rims size",
    "Fuel System" => "Fuel System",
    "Valvetrain" => "Valvetrain",  
  ];



  $pattern =[
    "id" => "id",
    "Brand" =>"Brand",
    "Model" => "Model",
    "Generation" =>  "Generation", 
    "Modification (Engine)" =>"Modification (Engine)",
    "Start of production" => "Start of production",
    "End of production" => "End of production",
    "Powertrain Architecture" => "Powertrain Architecture",
    "Body type" => "Body type",
    "Seats" => "Seats",
    "Doors" => "Doors",

    "Fuel consumption (economy) - urban" => "Fuel consumption (economy) - urban (l∕100 km)",
    "Fuel consumption (economy) - extra urban" => "Fuel consumption (economy) - extra urban (l∕100 km)",
    "Fuel consumption (economy) - combined" => "Fuel consumption (economy) - combined (l∕100 km)",
    "Fuel consumption (economy) - urban (Ethanol - E85)" => "Fuel consumption (economy) - urban (Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - extra urban (Ethanol - E85)" => "Fuel consumption (economy) - extra urban(Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - combined (Ethanol - E85)" => "Fuel consumption (economy) - combined(Ethanol - E85)(l∕100 km)",
    "Fuel consumption (economy) - urban (LPG)" => "Fuel consumption (economy) - urban (LPG)(l∕100 km)",
    "Fuel consumption (economy) - extra urban (LPG)" => "Fuel consumption (economy) - extra urban (LPG)(l∕100 km)",
    "Fuel consumption (economy) - combined (LPG)" => "Fuel consumption (economy) - combined (LPG)(l∕100 km)",
    "Fuel consumption (economy) - urban (CNG)" => "Fuel consumption (economy) - urban (CNG)(kg∕100 km)",
    "Fuel consumption (economy) - extra urban (CNG)" => "Fuel consumption (economy) - extra urban (CNG)(kg∕100 km)",
    "Fuel consumption (economy) - combined (CNG)" => "Fuel consumption (economy) - combined (CNG)(kg∕100 km)",
 
    "Fuel tank capacity" => "Fuel tank capacity (l)",
    "Fuel tank capacity (LPG)" => "Fuel tank capacity (LPG)(l)",
    "CNG cylinder capacity" => "CNG cylinder capacity (kg)",
    
    "CO" => "CO (g∕km)",
    "Emission standard" => "Emission standard",
    "AdBlue tank" => "AdBlue tank (l)",
    "Fuel Type" => "Fuel Type",

    "Average Energy consumption" => "Average Energy consumption(kWh∕100 km)",
    "Battery voltage" => "Battery voltage (V)",
    "Battery technology" => "Battery technology",
    "Gross battery capacity" => "Gross battery capacity (kWh)",
    "Net (usable) battery capacity" => "Net (usable) battery capacity (kWh)" ,
    "Recuperation output" =>  "Recuperation output (kW)",

    "All-electric range" =>  "All-electric range (km)",

    "Drag coefficient (C" => "Aerodynamic drag coefficient (Cₓ)",
    
    "Acceleration 0 - 100 km/h" => "Acceleration 0 - 100 km∕h (sec)",
    "Acceleration 0 - 100 km/h (LPG)" => "Acceleration 0 - 100 km∕h (LPG)(sec)",
    "Acceleration 0 - 100 km/h (CNG)" => "Acceleration 0 - 100 km∕h (CNG)(sec)",
    "Acceleration 0 - 300 km/h" => "Acceleration 0 - 300 km∕h (sec)",
    "Acceleration 0 - 200 km/h" => "Acceleration 0 - 200 km∕h (sec)",
    "Acceleration 0 - 62 mph" => "Acceleration 0 - 62 mph (sec)",
    "Acceleration 0 - 60 mph" => "Acceleration 0 - 60 mph (sec)",
    "Maximum speed" => "Maximum speed (km∕h)",
    "Maximum speed (LPG)" => "Maximum speed (LPG)(km∕h)",
    "Maximum speed (CNG)" => "Maximum speed (CNG)(km∕h)",
    "Max speed (electric)" =>"Maximum speed (electric) (km∕h)",
   
    "Maximum engine speed" => "Maximum engine speed rpm.",

    "Power" => "Power (Hp)",
    "Power (LPG)" => "Power (LPG)(Hp)",
    "Power (CNG)" => "Power (CNG)(Hp)",
    "Power (Ethanol - E85)" => "Power (Ethanol - E85)(Hp)",
    "System power" => "System power (Hp)",


    "Max power rpm."=>"Max power rpm.", 
    "Max power (LPG) rpm."=>"Max power (LPG) rpm.", 
    "Max power (CNG) rpm."=>"Max power (CNG) rpm.", 
    "Max power (Ethanol - E85) rpm."=>"Max power (Ethanol - E85) rpm.", 
    "Max system power rpm." => "Max system power rpm.",
    
    "Weight-to-power ratio" => "Weight-to-power ratio (kg∕Hp)",
    "Weight-to-power ratio (Hp∕tonne)" => "Weight-to-power ratio (Hp∕tonne)",
    


  
    "Torque" => "Torque (Nm)",
    "Torque (LPG)" => "Torque (LPG)(Hp)",
    "Torque (CNG)" => "Torque (CNG)(Hp)",
    "Torque (Ethanol - E85)" => "Torque (Ethanol - E85)(Hp)",
    "System torque" =>  "System torque (Nm)",

  
    "Max torque rpm."=>"Max torque rpm.", 
    "Max torque (LPG) rpm."=>"Max torque (LPG) rpm.", 
    "Max torque (CNG) rpm."=>"Max torque (CNG) rpm.", 
    "Max torque (Ethanol - E85) rpm."=>"Max torque (Ethanol - E85) rpm.", 
    "Max system torque rpm."=>"Max system torque rpm.", 

    "Weight-to-torque ratio"=> "Weight-to-torque ratio (kg∕Nm)",
    "Weight-to-torque ratio (Nm∕tonne)"=> "Weight-to-torque ratio (Nm∕tonne)",



    "Power per litre" => "Power per litre (Hp∕l)",
    "Power per litre (LPG)" => "Power per litre (LPG)(Hp∕l)",
    "Power per litre (CNG)" => "Power per litre (CNG)(Hp∕l)",
    "Power per litre (Ethanol - E85)" => "Power per litre (Ethanol - E85)(Hp∕l)",
   
    "Engine Model/Code" => "Engine Model∕Code",
    "Engine location" => "Engine location",
    "Engine displacement" => "Engine displacement (cm³)",
    "Number of cylinders" => "Number of cylinders",
    "Position of cylinders" => "Position of cylinders",
    "Compression ratio" =>  "Compression ratio",
    "Number of valves per cylinder" => "Number of valves per cylinder",
    "Engine aspiration" => "Engine aspiration",
    "Engine systems" =>  "Engine systems",
    
    "Cylinder Bore" => "Cylinder Bore (mm)",
    "Piston Stroke" => "Piston Stroke (mm)",
    "Engine oil capacity" => "Engine oil capacity (l)",
    "Coolant" => "Coolant (l)",         
    "Oil viscosity" =>  "Oil viscosity",
    "Engine oil specification" => "Engine oil specification", 
    "Kerb Weight" => "Kerb weight (kg)",
    "Max. weight" => "Max. weight (kg)",
    "Max load" => "Max load (kg)",
    "Trunk (boot) space - minimum" => "Trunk (boot) space - minimum (l)",
    "Trunk (boot) space - maximum" => "Trunk (boot) space - maximum (l)",  
    "Max. roof load" => "Max. roof load (kg)",
    "Permitted trailer load with brakes (12%)"=>"Permitted trailer load with brakes 12% (kg)",
    "Permitted trailer load with brakes (8%)"=>"Permitted trailer load with brakes 8% (kg)",
    "Permitted trailer load without brakes" => "Permitted trailer load without brakes (kg)",
    "Permitted towbar download" => "Permitted towbar download (kg)",
    "Length" => "Length (mm)",
    "Width" => "Width (mm)",
    "Width including mirrors" => "Width including mirrors (mm)",
    "Width with mirrors folded" => "Width with mirrors folded (mm)",
    "Height" => "Height (mm)",
    "Wheelbase" => "Wheelbase (mm)",
    "Front track" => "Front track (mm)", 
    "Rear (Back) track" => "Rear (Back) track (mm)",
    "Front overhang" =>"Front overhang (mm)",
    "Rear overhang" => "Rear overhang (mm)",
    "Minimum turning circle (turning diameter)" => "Minimum u-turn diameter (m)",
    "Ride height (ground clearance)" =>  "Ground clearance (mm)",
    "Wading depth" =>  "Wading depth (mm)",
    "Approach angle" => "Approach angle (%)",
    "Ramp-over (brakeover) angle" => "Ramp-over (brakeover) angle (%)",
    "Departure angle" => "Departure angle (%)",
    "Climb angle" =>  "Climb angle (%)",
    "Drive wheel" => "Drive wheel",
    "Drivetrain Architecture" =>"Drivetrain Architecture",
    "Number of Gears (manual transmission)" => "Number of Gears (manual transmission)",
    "Number of Gears (automatic transmission)" => "Number of Gears (automatic transmission)",
    "Front suspension" => "Front suspension",
    "Rear suspension" => "Rear suspension",
    "Front brakes" => "Front brakes",
    "Rear brakes" => "Rear brakes",
    "Assisting systems" =>  "Assisting systems",
    "200 km/h - 0" => "200 km∕h - 0 (m)",
    "100 km/h - 0" => "100 km∕h - 0 (m)",
    "Steering type" => "Steering type",
    "Power steering" =>  "Power steering",
    "Tires size" =>  "Tires size",
    "Wheel rims size" => "Wheel rims size",
   
    "Fuel System" => "Fuel System",
    "Valvetrain" => "Valvetrain",  
  ]
?>